In [3]:
import pandas as pd

%pip install openpyxl
df = pd.read_excel("../data/raw/crime_data.xlsx", engine="openpyxl")
df.head()

df.head()

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

,This tab outlines the contents of the datacube and includes links to relevant webpages on the ABS website. It ranges from cell A1 to B18.,Unnamed: 1
0,Australian Bureau of Statistics,NaN
1,"Recorded Crime – Offenders, 2024–25",NaN
2,Released at 11.30am (Canberra time) Wednesday ...,NaN
3,Contents,NaN
4,Tab,Description

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                     --------------  -----
 0   This tab outlines the contents of the datacube and includes links to relevant webpages on the ABS website. It ranges from cell A1 to B18.  17 non-null     str
 1   Unnamed: 1                                                                                                                                 6 non-null      str
dtypes: str(2)
memory usage: 1.3 KB

In [5]:
df.describe()

,This tab outlines the contents of the datacube and includes links to relevant webpages on the ABS website. It ranges from cell A1 to B18.,Unnamed: 1
count,17,6
unique,17,6
top,Australian Bureau of Statistics,Description
freq,1,1